### ISSUE TITLE
how to set up 2 players if you have 2 speakers 

### ISSUE THREAD

**Issue by bamer** [emiham/snapclient-ha#1]
on the windows or android snapclient players are created for each audio output (analog, and 2 connected bluetooth speaker)
in the config i have to choose only one, is there a solution to have them automaticaly create ?

**Comment by emiham** [comment]
I think this is a more general Snapcast question, not specific to the HA version, unless I'm misunderstanding you. 

What is it that you would like to have automatically created?

**Comment by bamer** [comment]
Maybe it's me who misuse snapclient on ha, because I don't have a gui or dont know how to access it, but on android (or windows) if I have 2 or 3 Bluetooth speakers and local analog device  connected I have the corresponding payers  created that I can enable or auto enable for the snapserver to see them and stream music on it,

Sorry if it's me who maybe don't have catch how to use it correctly on ha
In configuration before launching the add-on I can choose one output only even if ha correctly list all my pulse audio sink, and for the one I choose it work perfectly I wish that I can choose all I want , I hope it's more clear?
English is not my native language, I'm apologize if I have don't explain good enough,

**Comment by emiham** [comment]
So the other clients work, only the HA one doesn't? 

> I have the corresponding payers created that I can enable or auto enable for the snapserver to see them and stream music on it

Where are you enabling them?

**Comment by bamer** [comment]
Directly In the gui on windows or android, is there a web gui or integration  for the snapclient on ha ? 
On your ha module before run it I go to config tab and  I can choose only one at the end of the tab name  => output  (all are listed there already)
How do you configure 2 speakers on the snapclient on HA ? Internal sound card and one Bluetooth? I think it's not a bug but maybe I just miss or don't know how to do

**Comment by bamer** [comment]
My setup is :I have a snap server on a nas, I have android tablette with 2 speaker in a room and a windows pc with 3 speakers in an other room, the ha server is in my office and there I have 2 speaker, on other machine I have snapclient too everything work
It just for the ha version, it work but I only on 1 speaker at a time (the one a choose in the config tab)  if I can multi select them maybe  it should work,

**Comment by emiham** [comment]
> Directly In the gui on windows or android,

Could you take a screenshot of this and show me?

> On your ha module before run it I go to config tab and I can choose only one at the end of the tab name => output (all are listed there already)

As well as what this looks like for you.

**Comment by bamer** [comment]
Hello, i'm not home curently and for at least the next 10 days,
i will try to do it remotely sorry if there is delay

**Comment by emiham** [comment]
No worries, take your time.

**Comment by emiham** [comment]
@bamer Did you get a chance to look at this?

**Comment by emiham** [comment]
Closing since there is no way to move forward without a response. Feel free to reopen if you still have the same problem.
